snowflake-dw:
  target: dev
    outputs:
      dev:
        type: snowflake
        account: me73385.us-east4.gcp

        #autenticação
        user: AIRBYTE_USER
        password: AIRBYTE_PASSWORD

        #conexão
        role: AIRBYTE_ROLE
        database: AIRBYTE_DATABASE
        warehouse: AIRBYTE_WAREHOUSE
        schema: AIRBYTE_SCHEMA
        threads: 1
        client_session_keep_alive: False
        query_tag: dbt-q

        #opcional
        connect_retries: 0
        connect_timeout: 10
        retry_on_database_errors: False
        retry_all: False


